Repository DoYous/Senials-Frontend, pull requests merged in 2024-11, with the labels that each got.

#17 [design/frontend-13/party/partymember-check] 모임 세부 일정 참여 멤버 조회 창 디자인 구성
  senials_frontend/package-lock.json
  senials_frontend/package.json
  senials_frontend/src/App.js
  senials_frontend/src/pages/party/partyMember.js
  senials_frontend/src/pages/party/partyMember.module.css
Labels: 🎨Design

#18 [design/frontend-14/party/partyreview-write] 모임 게시판 후기 작성 페이지 디자인 구성
  senials_frontend/package-lock.json
  senials_frontend/package.json
  senials_frontend/src/App.js
  senials_frontend/src/pages/party/partyMember.js
  senials_frontend/src/pages/party/partyMember.module.css
  senials_frontend/src/pages/party/partyReview.js
  senials_frontend/src/pages/party/partyReview.module.css
Labels: 🎨Design

#20 [design/frontend-5/party/board] 모임 목록 - 레이아웃 설계
  senials_frontend/src/App.js
  senials_frontend/src/index.js
  senials_frontend/src/layouts/Layout.js
  senials_frontend/src/pages/party/Board.js
  senials_frontend/src/pages/party/Board.module.css
Labels: 🎨Design

#21 [design/frontend-15/party/partymeet-write] 모임 게시판 상세 일정 추가 페이지 디자인 구성
  senials_frontend/src/pages/party/partyReview.module.css
Labels: 🎨Design

#22 [design/frontend-6/party/board-overview] 모임 목록 전체보기 - 레이아웃 설계
  senials_frontend/src/App.js
  senials_frontend/src/pages/party/BoardOverview.js
  senials_frontend/src/pages/party/BoardOverview.module.css
Labels: 🎨Design

#24 [design/frontend-8/party/write] 모임 작성 - 레이아웃 설계
  senials_frontend/src/App.js
  senials_frontend/src/pages/party/BoardWrite.js
  senials_frontend/src/pages/party/BoardWrite.module.css
Labels: 🎨Design

#25 [design/frontend-9/party/update] 모임 수정 - 레이아웃 설계
  senials_frontend/src/App.js
  senials_frontend/src/pages/party/BoardUpdate.js
  senials_frontend/src/pages/party/BoardUpdate.module.css
Labels: 🎨Design

#27 [design/frontend-16/mypage/mypageAll] 마이페이지의 모든 페이지 디자인 구성
  senials_frontend/src/pages/mypage/mypageCalender.js
  senials_frontend/src/pages/mypage/mypageCalender.module.css
  senials_frontend/src/pages/party/partyReview.js
Labels: 🎨Design

#28 [design/frontend-11/search/unified-search-result] 통합검색 결과 - 레이아웃 설계
  senials_frontend/src/App.js
  senials_frontend/src/layouts/Layout.js
  senials_frontend/src/pages/search/WholeSearch.js
  senials_frontend/src/pages/search/WholeSearch.module.css
Labels: 🎨Design

#23 [design/frontend-1/suggest-custom-hobby/get-hobby] 맞춤형 취미 게시판 정보 입력 페이지 디자인 구성
  senials_frontend/public/img/suggest-hobby-background-img.png
  senials_frontend/src/App.js
  senials_frontend/src/index.js
  senials_frontend/src/pages/suggest-hobby/suggest-hobby-get.js
  senials_frontend/src/pages/suggest-hobby/suggest-hobby-get.module.css
Labels: 🎨Design

#26 [design/frontend-2/suggest-custom-hobby/post-hobby] 맞춤형 취미 추천 결과 페이지 디자인 구성
  senials_frontend/public/img/sampleImg.png
  senials_frontend/public/img/sampleImg2.png
  senials_frontend/src/App.js
  senials_frontend/src/pages/suggest-hobby/suggest-hobby-post.js
  senials_frontend/src/pages/suggest-hobby/suggest-hobby-post.module.css
Labels: 🎨Design

#29 [design/frontend-3/hobby-board/post-hobby-board] 취미 게시판 목록 전체보기 페이지 디자인 구성
  senials_frontend/public/img/sampleImg3.png
  senials_frontend/src/App.js
  senials_frontend/src/pages/hobby/hobby-board-post.js
  senials_frontend/src/pages/hobby/hobby-board-post.module.css
Labels: 🎨Design

#30 누락된 파일 추가
  senials_frontend/src/pages/mypage/mypage.js
  senials_frontend/src/pages/mypage/mypage.module.css
  senials_frontend/src/pages/mypage/mypageLike.js
  senials_frontend/src/pages/mypage/mypageLike.module.css
  senials_frontend/src/pages/mypage/mypageMember.js
  senials_frontend/src/pages/mypage/mypageMember.module.css
  senials_frontend/src/pages/mypage/mypageModify.js
  senials_frontend/src/pages/mypage/mypageModify.module.css
  senials_frontend/src/pages/party/partyMeet.js
  senials_frontend/src/pages/party/partyMeet.module.css
  senials_frontend/src/pages/party/partyMember.js
  senials_frontend/src/pages/party/partyMember.module.css
  senials_frontend/src/pages/party/partyReview.js
  senials_frontend/src/pages/party/partyReview.module.css
Labels: 🎨Design

#39 이걸 가장 먼저 머지해야함!! [design/frontend-31/common/common-modify]body 태그 주석 처리, 클래스 명으로 꾸민 css 제외 하고 공통 태그 사용한 부분 삭제
  senials_frontend/src/App.js
  senials_frontend/src/pages/hobby/hobby-board-post.module.css
  senials_frontend/src/pages/mypage/mypageCalender.module.css
  senials_frontend/src/pages/mypage/mypageMember.module.css
  senials_frontend/src/pages/mypage/mypageModify.module.css
  senials_frontend/src/pages/party/partyMeet.js
  senials_frontend/src/pages/party/partyMeet.module.css
  senials_frontend/src/pages/party/partyReview.js
  senials_frontend/src/pages/party/partyReview.module.css
  senials_frontend/src/pages/suggest-hobby/suggest-hobby-get.module.css
Labels: 🎨Design

#40 [design/frontend-32/mypageparty/modify-all] 마이페이지, 모임페이지 디자인 수정
  senials_frontend/src/pages/common/common.module.css
  senials_frontend/src/pages/mypage/mypageCalender.js
  senials_frontend/src/pages/mypage/mypageCalender.module.css
  senials_frontend/src/pages/mypage/mypageLike.js
  senials_frontend/src/pages/mypage/mypageLike.module.css
  senials_frontend/src/pages/mypage/mypageMember.js
  senials_frontend/src/pages/mypage/mypageMember.module.css
  senials_frontend/src/pages/mypage/mypageModify.js
  senials_frontend/src/pages/mypage/mypageModify.module.css
  senials_frontend/src/pages/party/partyMeet.js
  senials_frontend/src/pages/party/partyMeet.module.css
  senials_frontend/src/pages/party/partyMember.js
  senials_frontend/src/pages/party/partyMember.module.css
  senials_frontend/src/pages/party/partyReview.js
  senials_frontend/src/pages/party/partyReview.module.css
Labels: 🎨Design

#34 [design/frontend-12/hobby-board/get-hobby-review] 취미게시판 후기 생성 페이지 디자인 구성
  senials_frontend/src/App.js
  senials_frontend/src/pages/hobby/HobbyReviewGet.js
  senials_frontend/src/pages/hobby/HobbyReviewGet.module.css
Labels: 🎨Design

#44 [design/frontend-43/hobby-board/modify-hobby-review] 취미게시판 후기 수정 페이지 디자인 구성
  senials_frontend/src/App.js
  senials_frontend/src/pages/hobby/HobbyReviewModify.js
Labels: 🎨Design

#35 [design/frontend-10/mainpage] 메인페이지 - 레이아웃 설계
  senials_frontend/public/image/arrow-left.png
  senials_frontend/public/image/arrow-right.png
  senials_frontend/src/App.js
  senials_frontend/src/pages/mainpage/MainPage.js
  senials_frontend/src/pages/mainpage/MainPage.module.css
Labels: 🎨Design

#50 [hotfix/frontend-49/App.js] App.js 레이아웃 컴포넌트 import 중복 수정
  senials_frontend/src/App.js
Labels: 🚨Bug, 🎨Design

#58 [design/frontend-56/search/unified-search-result] 통합검색 결과 - 레이아웃 보강
  senials_frontend/src/pages/search/WholeSearch.js
  senials_frontend/src/pages/search/WholeSearch.module.css
Labels: 💪Enhancement, 🎨Design

#61 [design/frontend-42/mypage] 마이페이지 완성, 각종 모임 목록 페이지 레이아웃 구성
  senials_frontend/src/App.js
  senials_frontend/src/pages/mypage/mypage.js
  senials_frontend/src/pages/mypage/mypageCalender.module.css
  senials_frontend/src/pages/mypage/mypageLikedParty.js
  senials_frontend/src/pages/mypage/mypageMade.js
  senials_frontend/src/pages/mypage/mypageMember.js
  senials_frontend/src/pages/mypage/mypageModify.js
  senials_frontend/src/pages/mypage/mypageParticipate.js
Labels: 🎨Design

#63 [design/frontend-62/common/font] 공통 폰트 적용 및 글씨 크기, 버튼 크기 조정
  senials_frontend/public/index.html
  senials_frontend/src/index.js
  senials_frontend/src/pages/common/common.module.css
Labels: 🎨Design

#66 [design/frontend-60/party/boards] 모임 목록, 목록 전체보기 - 레이아웃 보강
  senials_frontend/src/pages/common/MainVer1.module.css
  senials_frontend/src/pages/mainpage/MainPage.js
  senials_frontend/src/pages/party/Board.js
  senials_frontend/src/pages/party/Board.module.css
  senials_frontend/src/pages/party/BoardOverview.js
  senials_frontend/src/pages/party/BoardOverview.module.css
Labels: 💪Enhancement, 🎨Design

#67 [design/frontend-32/mypageparty/modify-all] 모임페이지, 마이페이지 버튼 크기 조정 및 오류 수정
  senials_frontend/src/pages/common/common.module.css
  senials_frontend/src/pages/mypage/mypage.js
  senials_frontend/src/pages/mypage/mypageCalender.js
  senials_frontend/src/pages/mypage/mypageCalender.module.css
  senials_frontend/src/pages/mypage/mypageLike.js
  senials_frontend/src/pages/mypage/mypageMember.js
  senials_frontend/src/pages/mypage/mypageMember.module.css
  senials_frontend/src/pages/mypage/mypageModify.js
  senials_frontend/src/pages/mypage/mypageModify.module.css
  senials_frontend/src/pages/party/partyMeet.js
  senials_frontend/src/pages/party/partyMeet.module.css
  senials_frontend/src/pages/party/partyMember.js
  senials_frontend/src/pages/party/partyMember.module.css
  senials_frontend/src/pages/party/partyReview.js
  senials_frontend/src/pages/party/partyReview.module.css
Labels: 🎨Design

#70 [design/frontend-41/party/modifyPage] 모임 일정 수정, 모임 리뷰 수정 페이지 생성
  senials_frontend/src/App.js
  senials_frontend/src/pages/mypage/MypageMember.js
  senials_frontend/src/pages/mypage/MypageMember.module.css
  senials_frontend/src/pages/party/PartyMeet.module.css
  senials_frontend/src/pages/party/PartyMeetModify.js
  senials_frontend/src/pages/party/PartyMember.module.css
  senials_frontend/src/pages/party/PartyReview.module.css
  senials_frontend/src/pages/party/PartyReviewModify.js
Labels: 🎨Design

#73 [design/frontend-71/unifying-css] CSS 통합
  senials_frontend/src/App.js
  senials_frontend/src/pages/common/MainVer1.module.css
  senials_frontend/src/pages/mainpage/MainPage.js
  senials_frontend/src/pages/mainpage/MainPage.module.css
  senials_frontend/src/pages/party/BoardUpdate.js
  senials_frontend/src/pages/party/BoardUpdate.module.css
  senials_frontend/src/pages/party/BoardWrite.js
  senials_frontend/src/pages/party/BoardWrite.module.css
  senials_frontend/src/pages/party/PartyBoard.js
  senials_frontend/src/pages/party/PartyBoardOverview.js
  senials_frontend/src/pages/party/PartyDetail.js
  senials_frontend/src/pages/party/PartyForm.module.css
  senials_frontend/src/pages/party/PartyUpdate.js
  senials_frontend/src/pages/party/PartyWrite.js
  senials_frontend/src/pages/search/SearchWhole.js
  senials_frontend/src/pages/search/WholeSearch.module.css
Labels: 💪Enhancement, 🎨Design

#75 [design/frontend-59/hobby-board/hobby-board] 취미 게시판 디자인 스타일 보강
  senials_frontend/public/img/reportIcon.png
  senials_frontend/src/pages/hobby/HobbyBoardPost.js
  senials_frontend/src/pages/hobby/HobbyBoardPost.module.css
  senials_frontend/src/pages/hobby/HobbyDetailPost.js
  senials_frontend/src/pages/hobby/HobbyDetailPost.module.css
  senials_frontend/src/pages/hobby/HobbyReviewGet.module.css
  senials_frontend/src/pages/hobby/HobbyTagBoardPost.js
  senials_frontend/src/pages/suggestHobby/SuggestHobbyGet.module.css
  senials_frontend/src/pages/suggestHobby/SuggestHobbyPost.module.css
Labels: 💪Enhancement, 🎨Design

#76 [design/frontend-59/hobby-board/hobby-board] 실행오류 css 변경 반영
  senials_frontend/src/pages/hobby/HobbyDetailPost.js
Labels: 🚨Bug, 🎨Design

#78 [feature/frontend-74/link-pages] 페이지 이동 설정
  senials_frontend/src/App.js
  senials_frontend/src/pages/common/MainVer1.module.css
  senials_frontend/src/pages/mainpage/MainPage.js
  senials_frontend/src/pages/party/PartyBoard.js
  senials_frontend/src/pages/party/PartyBoardOverview.js
  senials_frontend/src/pages/party/PartyDetail.js
  senials_frontend/src/pages/party/PartyDetail.module.css
  senials_frontend/src/pages/party/PartyForm.module.css
  senials_frontend/src/pages/party/PartyUpdate.js
  senials_frontend/src/pages/party/PartyWrite.js
  senials_frontend/src/pages/search/SearchWhole.js
Labels: ⚡Feature

#79 [feature/frontend-77/link-pages] 취미 관련 게시판 페이지 이동 설정
  senials_frontend/src/App.js
  senials_frontend/src/layouts/Header.js
  senials_frontend/src/pages/hobby/HobbyBoardPost.js
  senials_frontend/src/pages/hobby/HobbyDetailPost.js
  senials_frontend/src/pages/hobby/HobbyReviewGet.js
  senials_frontend/src/pages/hobby/HobbyReviewModify.js
  senials_frontend/src/pages/hobby/HobbyTagBoardPost.js
  senials_frontend/src/pages/suggestHobby/SuggestHobbyGet.js
  senials_frontend/src/pages/suggestHobby/SuggestHobbyPost.js
  senials_frontend/src/pages/suggestHobby/SuggestHobbyPost.module.css
Labels: ⚡Feature

#81 [feature/frontend-80/link-pages] 마이페이지, 모임 양식 페이지 연결 및 CSS 수정
  senials_frontend/src/App.js
  senials_frontend/src/layouts/Header.js
  senials_frontend/src/pages/common/Common.module.css
  senials_frontend/src/pages/mypage/MypageCalender.js
  senials_frontend/src/pages/mypage/MypageCalender.module.css
  senials_frontend/src/pages/mypage/MypageLike.js
  senials_frontend/src/pages/mypage/MypageLikedParty.js
  senials_frontend/src/pages/mypage/MypageMade.js
  senials_frontend/src/pages/mypage/MypageMember.js
  senials_frontend/src/pages/mypage/MypageMember.module.css
  senials_frontend/src/pages/mypage/MypageModify.js
  senials_frontend/src/pages/mypage/MypageModify.module.css
  senials_frontend/src/pages/mypage/MypageParticipate.js
  senials_frontend/src/pages/mypage/MypageParty.module.css
  senials_frontend/src/pages/party/PartyMeet.js
  senials_frontend/src/pages/party/PartyMeet.module.css
  senials_frontend/src/pages/party/PartyMeetModify.js
  senials_frontend/src/pages/party/PartyMember.js
  senials_frontend/src/pages/party/PartyReview.js
  senials_frontend/src/pages/party/PartyReview.module.css
  senials_frontend/src/pages/party/PartyReviewModify.js
Labels: ⚡Feature
