Repository DoYous/Senials-Frontend, pull requests merged in 2024-12, with the labels that each got.

#83 [design/frontend-82/admin/manage-user] 관리자 페이지 사용자 관리 페이지 디자인 구성
  senials_frontend/public/img/Bell.png
  senials_frontend/public/img/Book open.png
  senials_frontend/public/img/Bookmark.png
  senials_frontend/public/img/Check square.png
  senials_frontend/public/img/Git commit.png
  senials_frontend/public/img/User.png
  senials_frontend/public/img/Users.png
  senials_frontend/public/img/adminLogo.png
  senials_frontend/src/App.js
  senials_frontend/src/pages/admin/ManageUser.js
  senials_frontend/src/pages/admin/admin.module.css
Labels: 🎨Design

#85 [feature/frontend-84/redux/dir-structurer-composition]프론트앤드 Redux Toolkit 라이브러리 구조 구성
  senials_frontend/package-lock.json
  senials_frontend/package.json
  senials_frontend/src/index.js
  senials_frontend/src/pages/admin/ManageUser.js
  senials_frontend/src/redux/store.js
Labels: ⚡Feature

#92 [feature/frontend-88/partyboards-overview/list-request-api] 모임 목록 전체보기 REST API 호출
  package-lock.json
  senials_frontend/package-lock.json
  senials_frontend/package.json
  senials_frontend/public/img/NoImage.svg
  senials_frontend/public/index.html
  senials_frontend/src/pages/common/MainVer1.module.css
  senials_frontend/src/pages/party/PartyBoardComponent/PopularPartyBoards.js
  senials_frontend/src/pages/party/PartyBoardOverview.js
  senials_frontend/src/redux/partySlice.js
  senials_frontend/src/redux/store.js
Labels: ⚡Feature, 🎨Design

#97 [feature/frontend-87/hobbyboard/request-api] 취미 게시판 전체 보기 페이지 Rest api 호출
  senials_frontend/package.json
  senials_frontend/src/App.js
  senials_frontend/src/pages/hobby/HobbyBoardPost.js
  senials_frontend/src/redux/hobbySlice.js
  senials_frontend/src/redux/store.js
Labels: ⚡Feature

#102 [feature/frontend-98/hobbyboard_review/request-api] 취미 게시판 상세보기 페이지 Rest api 호출
  senials_frontend/package.json
  senials_frontend/src/App.js
  senials_frontend/src/pages/hobby/HobbyBoard.js
  senials_frontend/src/pages/hobby/HobbyBoard.module.css
  senials_frontend/src/pages/hobby/HobbyDetail.js
  senials_frontend/src/pages/hobby/HobbyDetail.module.css
  senials_frontend/src/pages/hobby/HobbyDetailPost.js
  senials_frontend/src/pages/hobby/HobbyReview.js
  senials_frontend/src/pages/hobby/HobbyReview.module.css
  senials_frontend/src/pages/hobby/HobbyReviewModify.js
  senials_frontend/src/pages/hobby/HobbyTagBoard.js
  senials_frontend/src/pages/suggestHobby/SuggestHobby.js
  senials_frontend/src/pages/suggestHobby/SuggestHobby.module.css
  senials_frontend/src/pages/suggestHobby/SuggestHobbyResult.js
  senials_frontend/src/pages/suggestHobby/SuggestHobbyResult.module.css
  senials_frontend/src/redux/hobbySlice.js
  senials_frontend/src/redux/store.js
Labels: ⚡Feature

#106 [feature/frontend-100/partyboards/detail-basic-infos] 모임 상세 기본 정보 REST API 호출 및 출력
  senials_frontend/src/pages/party/PartyBoardOverview.js
  senials_frontend/src/pages/party/PartyDetail.js
  senials_frontend/src/redux/partySlice.js
  senials_frontend/src/redux/store.js
Labels: ⚡Feature, 🎨Design

#109 [feature/frontend-101/partyboards/detail-additional-infos] 모임 상세 추가 정보 REST API 호출 및 출력
  senials_frontend/package.json
  senials_frontend/src/App.js
  senials_frontend/src/pages/party/PartyDetail.js
  senials_frontend/src/redux/partySlice.js
  senials_frontend/src/redux/store.js
Labels: 🎨Design

#113 [test/frontend-55/kakaologin] 카카오로그인 페이지 디자인, 기능구현 #55
  .idea/senials-frontend.iml
  senials_frontend/.idea/workspace.xml
  senials_frontend/package-lock.json
  senials_frontend/package.json
  senials_frontend/public/image/kakaologinbt.png
  senials_frontend/src/App.js
  senials_frontend/src/pages/login/Join.js
  senials_frontend/src/pages/login/Join.module.css
  senials_frontend/src/pages/login/KakaoCallBack.js
  senials_frontend/src/pages/login/Login.js
  senials_frontend/src/pages/login/Login.module.css
  senials_frontend/src/pages/login/Success.js
  senials_frontend/src/pages/mainpage/MainPage.js
Labels: ⚡Feature, 🎨Design

#114 [feature/frontend-105/hobbyboard_postreview_modify/request-api] 취미 게시판 리뷰 수정 페이지 Rest api 호출
  senials_frontend/src/pages/hobby/HobbyDetail.js
  senials_frontend/src/pages/hobby/HobbyReview.js
  senials_frontend/src/pages/hobby/HobbyReviewModify.js
Labels: ⚡Feature

#117 [feature/frontend-115/hobbyboard_suggesthobby/request-api] 취미 게시판 맞춤형 취미 추천 페이지 로직 설정 #115
  senials_frontend/src/pages/suggestHobby/SuggestHobby.js
Labels: ⚡Feature

#121 [feature/frontend-120/hobbyboard_suggesthobbyresult/request-api] 취미 게시판 맞춤형 취미 추천 결과 페이지 Rest api 호출
  senials_frontend/src/pages/suggestHobby/SuggestHobbyResult.js
  senials_frontend/src/pages/suggestHobby/SuggestHobbyResult.module.css
Labels: ⚡Feature

#122 [feature/frontend-110/partyboards/modify-request-api] 모임 수정 REST API 호출
  senials_frontend/src/pages/party/PartyDetail.js
  senials_frontend/src/pages/party/PartyUpdate.js
  senials_frontend/src/pages/party/PartyWrite.js
Labels: ⚡Feature, 🎨Design

#126 [feature/frontend-125/hobbyboard_hobbytag/request-api] 취미 게시판 취미 카테고리 페이지 Rest api 호출
  senials_frontend/package.json
  senials_frontend/src/layouts/Header.js
  senials_frontend/src/pages/hobby/HobbyTagBoard.js
Labels: ⚡Feature

#129 [feature/frontend-127/mainpage/request-api] 메인페이지 REST API 호출
  senials_frontend/src/App.js
  senials_frontend/src/pages/common/ScrollToTop.js
  senials_frontend/src/pages/mainpage/MainPage.js
  senials_frontend/src/pages/party/PartyBoard.js
  senials_frontend/src/pages/party/PartyBoardComponent/PopularPartyBoards.js
  senials_frontend/src/pages/party/PartyBoardOverview.js
Labels: ⚡Feature, 🎨Design

#131 [feature/frontend-128/search-whole/request-api] 검색 키워드를 통해 취미,모임 결과 조회 Rest api 호출
  senials_frontend/src/layouts/Header.js
  senials_frontend/src/pages/search/SearchWhole.js
Labels: ⚡Feature

#134 [feature/frontend-108/party/request-api] 모임페이지 양식 페이지 rest-api 호출
  senials_frontend/.idea/inspectionProfiles/Project_Default.xml
  senials_frontend/.idea/misc.xml
  senials_frontend/.idea/modules.xml
  senials_frontend/.idea/senials_frontend.iml
  senials_frontend/.idea/shelf/Uncommitted_changes_before_rebase__Changes_.xml
  senials_frontend/.idea/vcs.xml
  senials_frontend/src/App.js
  senials_frontend/src/pages/mypage/MypageCalender.js
  senials_frontend/src/pages/mypage/MypageLikedParty.js
  senials_frontend/src/pages/party/PartyMeet.js
  senials_frontend/src/pages/party/PartyMeetModify.js
  senials_frontend/src/pages/party/PartyReview.js
  senials_frontend/src/pages/party/PartyReviewModify.js
Labels: ⚡Feature

#136 [feature/frontend-133/meetmembers/request-api] 모임 일정 참여 멤버 목록 REST API 호출 및 데이터 출력
  senials_frontend/src/pages/party/PartyDetail.js
  senials_frontend/src/pages/party/PartyMember.js
Labels: ⚡Feature, 🎨Design

#138 [bugfix/frontend-137/ Missing_database_value] 취미리뷰 이용비용 항목 누락 수정
  senials_frontend/src/pages/hobby/HobbyDetail.js
  senials_frontend/src/pages/hobby/HobbyDetail.module.css
  senials_frontend/src/pages/hobby/HobbyReview.js
  senials_frontend/src/pages/hobby/HobbyReviewModify.js
Labels: 🚨Bug, 💪Enhancement

#139 [feature/frontend-116/loginTest] 프론트&백 로그인테스트
  senials_frontend/package.json
  senials_frontend/src/layouts/Header.js
  senials_frontend/src/layouts/Header.module.css
  senials_frontend/src/pages/hobby/HobbyDetail.js
  senials_frontend/src/pages/hobby/HobbyReview.js
  senials_frontend/src/pages/hobby/HobbyReviewModify.js
  senials_frontend/src/pages/login/Join.js
  senials_frontend/src/pages/login/Login.js
  senials_frontend/src/pages/mypage/MypageCalender.js
  senials_frontend/src/pages/mypage/MypageLike.js
  senials_frontend/src/pages/mypage/MypageLikedParty.js
  senials_frontend/src/pages/mypage/MypageMade.js
  senials_frontend/src/pages/mypage/MypageModify.js
  senials_frontend/src/pages/mypage/MypageParticipate.js
  senials_frontend/src/pages/party/PartyDetail.js
Labels: ⚡Feature

#141 [hotfix/frontend-140/partyboards/missing-character] 사라진 JSX 소괄호 문자 복구
  senials_frontend/src/pages/party/PartyDetail.js
Labels: 🚨Bug, ⚡Feature

#142 [feature/frontend-135/partyboards/modified-router-url] 모임 후기, 일정 작성 수정된 라우터 Path에 맞게 동작 수정
  senials_frontend/package.json
  senials_frontend/src/App.js
  senials_frontend/src/pages/party/PartyBoardOverview.js
  senials_frontend/src/pages/party/PartyDetail.js
Labels: ⚡Feature, 💪Enhancement

#150 [feature/frontend-148/hobby-board-suggestion/suggestion] 취미 건의 사항 레이아웃 설계
  senials_frontend/public/img/BookOpen.png
  senials_frontend/public/img/CheckSquare.png
  senials_frontend/public/img/GitCommit.png
  senials_frontend/src/App.js
  senials_frontend/src/pages/admin/ManageUser.js
  senials_frontend/src/pages/admin/Report.module.css
  senials_frontend/src/pages/admin/Suggestion.js
Labels: 🎨Design

#151 [feature/frontend-149/report/report] 신고 페이지 레이아웃 설계
  senials_frontend/src/App.js
  senials_frontend/src/pages/admin/ReportComponent.js
Labels: 🎨Design

#152 [design/frontend-86/admin/manage-report] 관리자 페이지 신고 관리 페이지 레이아웃 설계
  senials_frontend/src/pages/admin/ManageReport.js
  senials_frontend/src/pages/admin/ManageUser.js
  senials_frontend/src/pages/admin/admin.module.css
Labels: 🎨Design

#154 [feature/frontend-153/admin/manage_suggestion] 관리자 건의 관리 페이지 레이아웃 설계
  senials_frontend/src/App.js
  senials_frontend/src/pages/admin/ManageSuggestion.js
Labels: 🎨Design

#157 [feature/frontend-155/admin/manage_category] 관리자 카테고리 관리 페이지 레이아웃 설계
  senials_frontend/src/App.js
  senials_frontend/src/pages/admin/AdminNav.js
  senials_frontend/src/pages/admin/ManageCateogry.js
  senials_frontend/src/pages/admin/ManageReport.js
  senials_frontend/src/pages/admin/ManageSuggestion.js
  senials_frontend/src/pages/admin/ManageUser.js
  senials_frontend/src/pages/admin/admin.module.css
  senials_frontend/src/pages/hobby/HobbyDetail.js
Labels: 🎨Design

#162 [feature/frontend-161/reports/request-api] 신고 REST API 호출
  senials_frontend/src/index.js
  senials_frontend/src/pages/admin/ReportComponent.js
  senials_frontend/src/pages/common/MainVer1.module.css
  senials_frontend/src/pages/hobby/HobbyDetail.js
  senials_frontend/src/pages/party/PartyDetail.js
  senials_frontend/src/pages/party/PartyMember.js
Labels: ⚡Feature

#164 [feature/frontend-160/suggestion/rest-api] 건의 추가 페이지 건의 사항 추가 Rest api 호출, 구조 만들기
  senials_frontend/package.json
  senials_frontend/src/App.js
  senials_frontend/src/pages/admin/Suggestion.js
  senials_frontend/src/pages/hobby/HobbyBoard.js
Labels: ⚡Feature

#171 [feature/frontend-170/admin_managecategory/rest-api] 관리자 카테고리 관리 페이지 Rest api 호출, 구조 만들기
  senials_frontend/src/pages/admin/ManageCateogry.js
  senials_frontend/src/pages/admin/admin.module.css
Labels: ⚡Feature

#174 [design/frontend-173/admin/no-use-elements] 미사용 요소 삭제
  senials_frontend/package.json
  senials_frontend/src/pages/admin/AdminNav.js
  senials_frontend/src/pages/admin/ManageReport.js
  senials_frontend/src/pages/admin/ManageUser.js
  senials_frontend/src/pages/admin/admin.module.css
Labels: 💪Enhancement, 🎨Design

#178 [bugfix/frontend-177/unspecified-gender] 관리자 페이지 성별 출력 수정
  senials_frontend/src/App.js
  senials_frontend/src/pages/admin/ManageReport.js
  senials_frontend/src/pages/admin/ManageUser.js
  senials_frontend/src/pages/admin/ReportComponent.js
Labels: 💪Enhancement, 🎨Design
